FROM valkey/valkey:7.2.8-alpine

ARG TARGETARCH

ENV SENTINEL_PORT=26379

LABEL version=1.0 \
      arch=$TARGETARCH \
      description="A production grade performance tuned valkey docker image for opstree redis-operator"

RUN apk update && apk upgrade && apk add --no-cache bash

COPY sentinel.conf /etc/redis/sentinel.conf

COPY entrypoint-sentinel.sh /usr/bin/entrypoint-sentinel.sh

COPY healthcheck-Sentinel.sh /usr/bin/healthcheck.sh

RUN chown -R 1000:0 /etc/redis && \
    chmod -R g+rw /etc/redis && \
    mkdir -p /sentinel-data && \
    chown -R 1000:0 /sentinel-data && \
    chmod -R g+rw /sentinel-data && \
    chmod -R g+rw /var/run

VOLUME ["/sentinel-data"]

WORKDIR /sentinel-data

EXPOSE ${SENTINEL_PORT}

USER 1000

ENTRYPOINT ["/usr/bin/entrypoint-sentinel.sh"]
